/**
 * Amazon Location Service Places categories — the values `SearchNearby` accepts
 * in `Filter.IncludeCategories` / `Filter.ExcludeCategories`, and the
 * `Categories[].Id` values every Places response carries.
 *
 * Generated from the "Categories filters" table of
 * https://docs.aws.amazon.com/location/latest/developerguide/places-filtering.html
 * (fetched 2026-08-30, 438 entries, in the table's order). `unsupported`
 * names the GrabMaps regions (ap-southeast-1, ap-southeast-5) where a category
 * is not available; the API runs in ap-southeast-2, where every entry applies.
 *
 * The IDs are exact and not guessable: it is `petrol-gasoline_station`, not
 * `petrol_station`, and `bar_or_pub`, not `bar`. A wrong ID is not an error —
 * it is an empty result.
 */
export interface PlaceCategory {
  id: string
  name: string
  /** AWS Regions where the category is not available (GrabMaps regions). */
  unsupported?: readonly string[]
}

export const PLACE_CATEGORIES: readonly PlaceCategory[] = [
  {
    id: 'administrative_region',
    name: 'Administrative Region',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'administrative_region-streets',
    name: 'Administrative Region-Streets',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'adult_entertainment', name: 'Adult Entertainment' },
  {
    id: 'adult_shop',
    name: 'Adult Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'advertising-marketing,_pr_and_market_research',
    name: 'Advertising-Marketing, PR and Market Research',
  },
  { id: 'aerial_tramway', name: 'Aerial Tramway' },
  { id: 'airport', name: 'Airport' },
  { id: 'airport_cargo', name: 'Airport Cargo' },
  { id: 'airport_terminal', name: 'Airport Terminal' },
  { id: 'ambulance_services', name: 'Ambulance Services' },
  { id: 'amusement_park', name: 'Amusement Park' },
  { id: 'animal_park', name: 'Animal Park' },
  {
    id: 'apartment_rental-flat_rental',
    name: 'Apartment Rental-Flat Rental',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'aquarium', name: 'Aquarium' },
  { id: 'art_museum', name: 'Art Museum' },
  { id: 'arts_and_crafts_supplies', name: 'Arts and Crafts Supplies' },
  {
    id: 'ashram',
    name: 'Ashram',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'atm', name: 'ATM' },
  { id: 'attorney', name: 'Attorney' },
  { id: 'auto_parts', name: 'Auto Parts' },
  {
    id: 'automobile_club',
    name: 'Automobile Club',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'automobile_dealership-new_cars',
    name: 'Automobile Dealership-New Cars',
  },
  {
    id: 'automobile_dealership-used_cars',
    name: 'Automobile Dealership-Used Cars',
  },
  { id: 'aviation', name: 'Aviation' },
  { id: 'b2b_restaurant_services', name: 'B2B Restaurant Services' },
  { id: 'b2b_sales_and_services', name: 'B2B Sales and Services' },
  { id: 'badminton', name: 'Badminton' },
  { id: 'bakery_and_baked_goods_store', name: 'Bakery and Baked Goods Store' },
  { id: 'bank', name: 'Bank' },
  {
    id: 'banquet_hall',
    name: 'Banquet Hall',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'bar_or_pub', name: 'Bar or Pub' },
  { id: 'barber', name: 'Barber' },
  { id: 'basketball', name: 'Basketball' },
  {
    id: 'bay-harbor',
    name: 'Bay-Harbor',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'beach', name: 'Beach' },
  { id: 'bed_and_breakfast', name: 'Bed and Breakfast' },
  { id: 'beer_garden', name: 'Beer Garden' },
  {
    id: 'bicycle_and_bicycle_accessories_shop',
    name: 'Bicycle and Bicycle Accessories Shop',
  },
  {
    id: 'bicycle_parking',
    name: 'Bicycle Parking',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'bicycle_service',
    name: 'Bicycle Service',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'bicycle_service_and_maintenance',
    name: 'Bicycle Service and Maintenance',
  },
  { id: 'bicycle_sharing_location', name: 'Bicycle Sharing Location' },
  { id: 'bike_park', name: 'Bike Park' },
  { id: 'bill_payment_service', name: 'Bill Payment Service' },
  { id: 'billiards-pool_hall', name: 'Billiards-Pool Hall' },
  { id: 'bistro', name: 'Bistro' },
  { id: 'blood_bank', name: 'Blood Bank' },
  {
    id: 'bmx_shop',
    name: 'BMX Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'bmx_track',
    name: 'BMX Track',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'boat_ferry',
    name: 'Boat Ferry',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'boating', name: 'Boating' },
  { id: 'body_of_water', name: 'Body of Water' },
  { id: 'body_piercing_and_tattoos', name: 'Body Piercing and Tattoos' },
  { id: 'bookstore', name: 'Bookstore' },
  { id: 'border_crossing', name: 'Border Crossing' },
  { id: 'bowling_center', name: 'Bowling Center' },
  {
    id: 'brewery',
    name: 'Brewery',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'building', name: 'Building' },
  { id: 'bus_rapid_transit', name: 'Bus Rapid Transit' },
  { id: 'bus_station', name: 'Bus Station' },
  { id: 'bus_stop', name: 'Bus Stop' },
  { id: 'business_facility', name: 'Business Facility' },
  { id: 'business_service', name: 'Business Service' },
  { id: 'butcher', name: 'Butcher' },
  { id: 'cafeteria', name: 'Cafeteria' },
  { id: 'campground', name: 'Campground' },
  { id: 'camping-hiking_shop', name: 'Camping-Hiking Shop' },
  {
    id: 'campsite',
    name: 'Campsite',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'canal',
    name: 'Canal',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'canoe-kayak_shop',
    name: 'Canoe-Kayak Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'car_repair', name: 'Car Repair' },
  { id: 'car_repair-service', name: 'Car Repair-Service' },
  { id: 'car_wash-detailing', name: 'Car Wash-Detailing' },
  { id: 'cargo_center', name: 'Cargo Center' },
  { id: 'cargo_transportation', name: 'Cargo Transportation' },
  { id: 'carshare_location', name: 'Carshare Location' },
  { id: 'casino', name: 'Casino' },
  { id: 'castle', name: 'Castle' },
  { id: 'casual_dining', name: 'Casual Dining' },
  {
    id: 'catering_and_other_food_services',
    name: 'Catering and Other Food Services',
  },
  {
    id: 'cellphone_parking_lot',
    name: 'Cellphone Parking Lot',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'cemetery', name: 'Cemetery' },
  {
    id: 'check_cashing_service-currency_exchange',
    name: 'Check Cashing Service-Currency Exchange',
  },
  { id: "children's_apparel", name: "Children's Apparel" },
  { id: "children's_museum", name: "Children's Museum" },
  { id: 'chiropractor', name: 'Chiropractor' },
  { id: 'church', name: 'Church' },
  { id: 'cigar_and_tobacco_shop', name: 'Cigar and Tobacco Shop' },
  { id: 'cinema', name: 'Cinema' },
  { id: 'city_hall', name: 'City Hall' },
  { id: 'city,_town_or_village', name: 'City, Town or Village' },
  { id: 'civic-community_center', name: 'Civic-Community Center' },
  { id: 'clothing_and_accessories', name: 'Clothing and Accessories' },
  { id: 'clubhouse', name: 'Clubhouse' },
  { id: 'coaching_institute', name: 'Coaching Institute' },
  { id: 'cocktail_lounge', name: 'Cocktail Lounge' },
  { id: 'coffee_shop', name: 'Coffee Shop' },
  { id: 'coffee-tea', name: 'Coffee-Tea' },
  { id: 'collective_community', name: 'Collective Community' },
  { id: 'commercial_services', name: 'Commercial Services' },
  { id: 'communication-media', name: 'Communication-Media' },
  {
    id: 'commuter_rail_station',
    name: 'Commuter Rail Station',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'commuter_train',
    name: 'Commuter Train',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'complete_rest_area',
    name: 'Complete Rest Area',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'computer_and_software', name: 'Computer and Software' },
  { id: 'construction', name: 'Construction' },
  { id: 'consumer_electronics_store', name: 'Consumer Electronics Store' },
  { id: 'consumer_goods', name: 'Consumer Goods' },
  { id: 'consumer_services', name: 'Consumer Services' },
  { id: 'convenience_store', name: 'Convenience Store' },
  { id: 'convention-exhibition_center', name: 'Convention-Exhibition Center' },
  {
    id: 'county_council',
    name: 'County Council',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'couriers', name: 'Couriers' },
  { id: 'courthouse', name: 'Courthouse' },
  {
    id: 'covid-19_testing_site',
    name: 'COVID-19 Testing Site',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'crematorium', name: 'Crematorium' },
  {
    id: 'cross_country_ski_shop',
    name: 'Cross Country Ski Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'customer_care-service_center',
    name: 'Customer Care-Service Center',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'dairy_goods', name: 'Dairy Goods' },
  { id: 'dancing', name: 'Dancing' },
  { id: 'deli', name: 'Deli' },
  {
    id: 'delivery_entrance',
    name: 'Delivery Entrance',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'dentist-dental_office', name: 'Dentist-Dental Office' },
  { id: 'department_store', name: 'Department Store' },
  { id: 'discount_store', name: 'Discount Store' },
  {
    id: 'distillery',
    name: 'Distillery',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'diving_center', name: 'Diving Center' },
  {
    id: 'doughnut_shop',
    name: 'Doughnut Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'drugstore', name: 'Drugstore' },
  {
    id: 'drugstore_or_pharmacy',
    name: 'Drugstore or Pharmacy',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'dry_cleaning_and_laundry', name: 'Dry Cleaning and Laundry' },
  { id: 'education_facility', name: 'Education Facility' },
  { id: 'electrical', name: 'Electrical' },
  { id: 'embassy', name: 'Embassy' },
  { id: 'emission_testing', name: 'Emission Testing' },
  {
    id: 'engineering_and_scientific_services',
    name: 'Engineering and Scientific Services',
  },
  { id: 'entertainment_and_recreation', name: 'Entertainment and Recreation' },
  { id: 'entertainment_electronics', name: 'Entertainment Electronics' },
  {
    id: 'ev_battery_swap_station',
    name: 'EV Battery Swap Station',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'ev_charging_station', name: 'EV Charging Station' },
  {
    id: 'ev_charging_station_for_2-wheelers_and_light_vehicles',
    name: 'EV Charging Station for 2-wheelers and Light Vehicles',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'ev_charging_station_for_trucks',
    name: 'EV Charging Station for Trucks',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'ev_dealership-new_vehicles',
    name: 'EV Dealership-New Vehicles',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'ev_repair',
    name: 'EV Repair',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'event_spaces',
    name: 'Event Spaces',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'facilities', name: 'Facilities' },
  {
    id: 'family_restaurant',
    name: 'Family Restaurant',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'family-general_practice_physicians',
    name: 'Family-General Practice Physicians',
  },
  { id: 'farming', name: 'Farming' },
  { id: 'fast_food', name: 'Fast Food' },
  { id: 'ferry_terminal', name: 'Ferry Terminal' },
  { id: 'finance_and_insurance', name: 'Finance and Insurance' },
  { id: 'financial_investment_firm', name: 'Financial Investment Firm' },
  { id: 'fine_arts', name: 'Fine Arts' },
  {
    id: 'fine_dining',
    name: 'Fine Dining',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'fire_department', name: 'Fire Department' },
  { id: 'fitness-health_club', name: 'Fitness-Health Club' },
  { id: 'floor_and_carpet', name: 'Floor and Carpet' },
  { id: 'florist', name: 'Florist' },
  {
    id: 'flowers_and_jewelry',
    name: 'Flowers and Jewelry',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'food_market-stall', name: 'Food Market-Stall' },
  { id: 'food_production', name: 'Food Production' },
  {
    id: 'food-beverage_specialty_store',
    name: 'Food-Beverage Specialty Store',
  },
  {
    id: 'forest,_heath_or_other_vegetation',
    name: 'Forest, Heath or Other Vegetation',
  },
  { id: 'fueling_station', name: 'Fueling Station' },
  {
    id: 'fulfillment_and_distribution_center',
    name: 'Fulfillment and Distribution Center',
  },
  { id: 'funeral_director', name: 'Funeral Director' },
  { id: 'furniture_store', name: 'Furniture Store' },
  { id: 'gallery', name: 'Gallery' },
  { id: 'gambling-lottery-betting', name: 'Gambling-Lottery-Betting' },
  { id: 'garden', name: 'Garden' },
  { id: 'garden_center', name: 'Garden Center' },
  { id: 'general_merchandise', name: 'General Merchandise' },
  { id: 'gift,_antique_and_art', name: 'Gift, Antique and Art' },
  { id: 'glass_and_window', name: 'Glass and Window' },
  { id: 'golf_course', name: 'Golf Course' },
  { id: 'golf_practice_range', name: 'Golf Practice Range' },
  { id: 'golf_shop', name: 'Golf Shop' },
  { id: 'government_office', name: 'Government Office' },
  {
    id: 'government_or_community_facility',
    name: 'Government or Community Facility',
  },
  { id: 'grocery', name: 'Grocery' },
  { id: 'guest_house', name: 'Guest House' },
  { id: 'gurdwara', name: 'Gurdwara' },
  { id: 'hair_and_beauty', name: 'Hair and Beauty' },
  { id: 'hair_salon', name: 'Hair Salon' },
  { id: 'hardware,_house_and_garden', name: 'Hardware, House and Garden' },
  {
    id: 'healthcare_and_healthcare_support_services',
    name: 'Healthcare and Healthcare Support Services',
  },
  { id: 'higher_education', name: 'Higher Education' },
  { id: 'highway_entrance', name: 'Highway Entrance' },
  { id: 'highway_exit', name: 'Highway Exit' },
  { id: 'historical_monument', name: 'Historical Monument' },
  { id: 'history_museum', name: 'History Museum' },
  {
    id: 'hockey',
    name: 'Hockey',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'holiday_park', name: 'Holiday Park' },
  { id: 'home_improvement', name: 'Home Improvement' },
  { id: 'home_specialty_store', name: 'Home Specialty Store' },
  { id: 'hospital', name: 'Hospital' },
  { id: 'hospital_emergency_room', name: 'Hospital Emergency Room' },
  {
    id: 'hospital_or_health_care_facility',
    name: 'Hospital or Health Care Facility',
  },
  { id: 'hostel', name: 'Hostel' },
  { id: 'hot_spring', name: 'Hot Spring' },
  { id: 'hotel', name: 'Hotel' },
  { id: 'hotel_or_motel', name: 'Hotel or Motel' },
  {
    id: 'human_resources_and_recruiting_services',
    name: 'Human Resources and Recruiting Services',
  },
  { id: 'hunting-fishing_shop', name: 'Hunting-Fishing Shop' },
  {
    id: 'hydrogen_fuel_station',
    name: 'Hydrogen Fuel Station',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'ice_skating_rink', name: 'Ice Skating Rink' },
  { id: 'inclined_rail', name: 'Inclined Rail' },
  {
    id: 'indoor_ski',
    name: 'Indoor Ski',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'indoor_sports', name: 'Indoor Sports' },
  { id: 'industrial_zone', name: 'Industrial Zone' },
  { id: 'interior_and_exterior_design', name: 'Interior and Exterior Design' },
  { id: 'internet_cafe', name: 'Internet Cafe' },
  { id: 'intersection', name: 'Intersection' },
  { id: 'investigation_services', name: 'Investigation Services' },
  { id: 'island', name: 'Island' },
  {
    id: 'it_and_office_equipment_services',
    name: 'IT and Office Equipment Services',
  },
  { id: 'jazz_club', name: 'Jazz Club' },
  { id: 'jeweler', name: 'Jeweler' },
  { id: 'karaoke', name: 'Karaoke' },
  { id: 'kindergarten_and_childcare', name: 'Kindergarten and Childcare' },
  { id: 'lake', name: 'Lake' },
  { id: 'landmark-attraction', name: 'Landmark-Attraction' },
  { id: 'landscaping_services', name: 'Landscaping Services' },
  { id: 'language_studies', name: 'Language Studies' },
  { id: 'legal_services', name: 'Legal Services' },
  {
    id: 'leisure',
    name: 'Leisure',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'library', name: 'Library' },
  { id: 'lightrail', name: 'Lightrail' },
  { id: 'live_entertainment-music', name: 'Live Entertainment-Music' },
  {
    id: 'loading_dock',
    name: 'Loading Dock',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'loading_zone',
    name: 'Loading Zone',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'local_transit', name: 'Local Transit' },
  {
    id: 'locksmiths_and_security_systems_services',
    name: 'Locksmiths and Security Systems Services',
  },
  { id: 'lodging', name: 'Lodging' },
  { id: 'lottery_booth', name: 'Lottery Booth' },
  {
    id: 'lumber',
    name: 'Lumber',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'maid_services', name: 'Maid Services' },
  { id: 'major_appliance', name: 'Major Appliance' },
  {
    id: 'management_and_consulting_services',
    name: 'Management and Consulting Services',
  },
  { id: 'manufacturing', name: 'Manufacturing' },
  { id: 'marina', name: 'Marina' },
  { id: 'market', name: 'Market' },
  {
    id: 'marriage_and_match_making_services',
    name: 'Marriage and Match Making Services',
  },
  { id: 'medical_services-clinics', name: 'Medical Services-Clinics' },
  {
    id: 'meeting_point',
    name: 'Meeting Point',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: "men's_apparel", name: "Men's Apparel" },
  { id: 'military_base', name: 'Military Base' },
  {
    id: 'mining,_quarrying_and_other_extraction',
    name: 'Mining, Quarrying and Other Extraction',
  },
  { id: 'mobile_retailer', name: 'Mobile Retailer' },
  { id: 'mobile_service_center', name: 'Mobile Service Center' },
  {
    id: 'modeling_agencies',
    name: 'Modeling Agencies',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'money_transferring_service', name: 'Money Transferring Service' },
  { id: 'monorail', name: 'Monorail' },
  { id: 'mosque', name: 'Mosque' },
  { id: 'motel', name: 'Motel' },
  { id: 'motorcycle_accessories', name: 'Motorcycle Accessories' },
  { id: 'motorcycle_dealership', name: 'Motorcycle Dealership' },
  {
    id: 'motorcycle_service_and_maintenance',
    name: 'Motorcycle Service and Maintenance',
  },
  {
    id: 'motorcycle,_moped_and_scooter_parking',
    name: 'Motorcycle, Moped and Scooter Parking',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'motorway_service_rest_area',
    name: 'Motorway Service Rest Area',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'mountain_or_hill', name: 'Mountain or Hill' },
  { id: 'mountain_passes', name: 'Mountain Passes' },
  {
    id: 'mountain_peaks',
    name: 'Mountain Peaks',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'mover', name: 'Mover' },
  { id: 'museum', name: 'Museum' },
  { id: 'nail_salon', name: 'Nail Salon' },
  {
    id: 'named_intersection-chowk',
    name: 'Named Intersection-Chowk',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'natural_and_geographical', name: 'Natural and Geographical' },
  { id: 'night_club', name: 'Night Club' },
  { id: 'nightlife-entertainment', name: 'Nightlife-Entertainment' },
  { id: 'non-store_retailers', name: 'Non-Store Retailers' },
  { id: 'nursing_home', name: 'Nursing Home' },
  {
    id: 'off_road_trailhead',
    name: 'Off Road Trailhead',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'off-road_vehicle_area', name: 'Off-Road Vehicle Area' },
  {
    id: 'office_supply_and_services_store',
    name: 'Office Supply and Services Store',
  },
  { id: 'optical', name: 'Optical' },
  { id: 'organizations_and_societies', name: 'Organizations and Societies' },
  { id: 'other_bookshop', name: 'Other Bookshop' },
  {
    id: 'other_library',
    name: 'Other Library',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'other_place_of_worship', name: 'Other Place of Worship' },
  {
    id: 'outdoor_area-complex',
    name: 'Outdoor Area-Complex',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'outdoor_service',
    name: 'Outdoor Service',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'outdoor-recreation', name: 'Outdoor-Recreation' },
  {
    id: 'pagoda',
    name: 'Pagoda',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'paint_store', name: 'Paint Store' },
  { id: 'park_and_ride', name: 'Park and Ride' },
  { id: 'park-recreation_area', name: 'Park-Recreation Area' },
  { id: 'parking', name: 'Parking' },
  {
    id: 'parking_and_restroom_only_rest_area',
    name: 'Parking and Restroom Only Rest Area',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'parking_garage-parking_house', name: 'Parking Garage-Parking House' },
  {
    id: 'parking_lot',
    name: 'Parking Lot',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'parking_only_rest_area',
    name: 'Parking Only Rest Area',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'pawnshop', name: 'Pawnshop' },
  { id: 'performing_arts', name: 'Performing Arts' },
  { id: 'pet_care', name: 'Pet Care' },
  { id: 'pet_supply', name: 'Pet Supply' },
  { id: 'petrol-gasoline_station', name: 'Petrol-Gasoline Station' },
  { id: 'pharmacy', name: 'Pharmacy' },
  { id: 'photography', name: 'Photography' },
  { id: 'plumbing', name: 'Plumbing' },
  {
    id: 'police_box',
    name: 'Police Box',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'police_services-security', name: 'Police Services-Security' },
  { id: 'police_station', name: 'Police Station' },
  { id: 'post_office', name: 'Post Office' },
  {
    id: 'postal_area',
    name: 'Postal Area',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'postal_collection_box', name: 'Postal Collection Box' },
  { id: 'power_equipment_dealer', name: 'Power Equipment Dealer' },
  { id: 'primary_school', name: 'Primary School' },
  { id: 'printing_and_publishing', name: 'Printing and Publishing' },
  { id: 'property_management', name: 'Property Management' },
  { id: 'psychiatric_institute', name: 'Psychiatric Institute' },
  {
    id: 'public_administration',
    name: 'Public Administration',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'public_restroom-toilets', name: 'Public Restroom-Toilets' },
  { id: 'public_sports_airport', name: 'Public Sports Airport' },
  {
    id: 'public_transit_access',
    name: 'Public Transit Access',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'race_track', name: 'Race Track' },
  {
    id: 'racquetball_court',
    name: 'Racquetball Court',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'rail_ferry',
    name: 'Rail Ferry',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'rail_yard',
    name: 'Rail Yard',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'ranger_station',
    name: 'Ranger Station',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'real_estate_services', name: 'Real Estate Services' },
  { id: 'record,_cd_and_video', name: 'Record, CD and Video' },
  { id: 'recreation_center', name: 'Recreation Center' },
  { id: 'recycling_center', name: 'Recycling Center' },
  { id: 'registration_office', name: 'Registration Office' },
  { id: 'religious_place', name: 'Religious Place' },
  { id: 'rental_and_leasing', name: 'Rental and Leasing' },
  { id: 'rental_car_agency', name: 'Rental Car Agency' },
  {
    id: 'repair_and_maintenance_services',
    name: 'Repair and Maintenance Services',
  },
  { id: 'repair_service', name: 'Repair Service' },
  {
    id: 'reservoir',
    name: 'Reservoir',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'residential_area-building', name: 'Residential Area-Building' },
  { id: 'rest_area', name: 'Rest Area' },
  { id: 'restaurant', name: 'Restaurant' },
  { id: 'rideshare_pickup', name: 'Rideshare Pickup' },
  { id: 'river', name: 'River' },
  {
    id: 'road_assistance',
    name: 'Road Assistance',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'roadside_station',
    name: 'Roadside Station',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'rugby',
    name: 'Rugby',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'running_track', name: 'Running Track' },
  {
    id: 'running-walking_shop',
    name: 'Running-Walking Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'rv_parks',
    name: 'RV Parks',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'ryokan', name: 'Ryokan' },
  {
    id: 'scenic_overlook_rest_area',
    name: 'Scenic Overlook Rest Area',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'scenic_point', name: 'Scenic Point' },
  { id: 'school', name: 'School' },
  { id: 'science_museum', name: 'Science Museum' },
  { id: 'seaport-harbour', name: 'Seaport-Harbour' },
  { id: 'secondary_school', name: 'Secondary School' },
  { id: 'shoes-footwear', name: 'Shoes-Footwear' },
  { id: 'shooting_range', name: 'Shooting Range' },
  { id: 'shopping_mall', name: 'Shopping Mall' },
  { id: 'short-time_motel', name: 'Short-Time Motel' },
  { id: 'shrine', name: 'Shrine' },
  { id: 'skate_shop', name: 'Skate Shop' },
  {
    id: 'ski_lift',
    name: 'Ski Lift',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'ski_resort', name: 'Ski Resort' },
  { id: 'ski_shop', name: 'Ski Shop' },
  {
    id: 'snowboard_shop',
    name: 'Snowboard Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'soccer_club', name: 'Soccer Club' },
  { id: 'social_service', name: 'Social Service' },
  { id: 'specialty_clothing_store', name: 'Specialty Clothing Store' },
  { id: 'specialty_food_store', name: 'Specialty Food Store' },
  { id: 'specialty_store', name: 'Specialty Store' },
  { id: 'specialty_trade_contractors', name: 'Specialty Trade Contractors' },
  { id: 'sporting_goods_store', name: 'Sporting Goods Store' },
  {
    id: 'sporting_instruction_and_camps',
    name: 'Sporting Instruction and Camps',
  },
  { id: 'sports_activities', name: 'Sports Activities' },
  { id: 'sports_complex-stadium', name: 'Sports Complex-Stadium' },
  { id: 'sports_facility-venue', name: 'Sports Facility-Venue' },
  { id: 'sports_field', name: 'Sports Field' },
  { id: 'squash_court', name: 'Squash Court' },
  { id: 'storage', name: 'Storage' },
  { id: 'street_or_square', name: 'Street or Square' },
  { id: 'student_housing', name: 'Student Housing' },
  { id: 'surf_shop', name: 'Surf Shop' },
  { id: 'sweet_shop', name: 'Sweet Shop' },
  { id: 'swimming_pool', name: 'Swimming Pool' },
  { id: 'synagogue', name: 'Synagogue' },
  {
    id: 'tack_shop',
    name: 'Tack Shop',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'tailor_and_alteration', name: 'Tailor and Alteration' },
  { id: 'take_out_and_delivery_only', name: 'Take Out and Delivery Only' },
  { id: 'tanning_salon', name: 'Tanning Salon' },
  { id: 'taqueria', name: 'Taqueria' },
  { id: 'tax_service', name: 'Tax Service' },
  { id: 'taxi_stand', name: 'Taxi Stand' },
  { id: 'tea_house', name: 'Tea House' },
  { id: 'telephone_service', name: 'Telephone Service' },
  { id: 'temple', name: 'Temple' },
  { id: 'tennis_court', name: 'Tennis Court' },
  { id: 'theatre,_music_and_culture', name: 'Theatre, Music and Culture' },
  { id: 'therapist', name: 'Therapist' },
  { id: 'tire_repair', name: 'Tire Repair' },
  { id: 'tollbooth', name: 'Tollbooth' },
  { id: 'tourist_attraction', name: 'Tourist Attraction' },
  { id: 'tourist_information', name: 'Tourist Information' },
  { id: 'towing_service', name: 'Towing Service' },
  { id: 'toy_store', name: 'Toy Store' },
  { id: 'trailhead', name: 'Trailhead' },
  { id: 'train_station', name: 'Train Station' },
  { id: 'training_and_development', name: 'Training and Development' },
  {
    id: 'translation_and_interpretation_services',
    name: 'Translation and Interpretation Services',
  },
  { id: 'transportation_service', name: 'Transportation Service' },
  { id: 'travel_agent-ticketing', name: 'Travel Agent-Ticketing' },
  { id: 'truck_dealership', name: 'Truck Dealership' },
  {
    id: 'truck_parking',
    name: 'Truck Parking',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'truck_repair', name: 'Truck Repair' },
  {
    id: 'truck_stop-plaza',
    name: 'Truck Stop-Plaza',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  {
    id: 'truck_wash',
    name: 'Truck Wash',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'truck-semi_dealer-services', name: 'Truck-Semi Dealer-Services' },
  { id: 'underground_train-subway', name: 'Underground Train-Subway' },
  { id: 'undersea_feature', name: 'Undersea Feature' },
  { id: 'urgent_care_center', name: 'Urgent Care Center' },
  {
    id: 'used-second_hand_merchandise_stores',
    name: 'Used-Second Hand Merchandise Stores',
  },
  { id: 'utilities', name: 'Utilities' },
  { id: 'vaccination_site', name: 'Vaccination Site' },
  {
    id: 'van_repair',
    name: 'Van Repair',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'vaping_store', name: 'Vaping Store' },
  {
    id: 'variety_store',
    name: 'Variety Store',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'veterinarian', name: 'Veterinarian' },
  { id: 'video_and_game_rental', name: 'Video and Game Rental' },
  { id: 'video_arcade-game_room', name: 'Video Arcade-Game Room' },
  { id: 'warehouse', name: 'Warehouse' },
  { id: 'waste_and_sanitary', name: 'Waste and Sanitary' },
  { id: 'water_park', name: 'Water Park' },
  { id: 'water_transit', name: 'Water Transit' },
  { id: 'waterfall', name: 'Waterfall' },
  {
    id: 'wedding_services_and_bridal_studio',
    name: 'Wedding Services and Bridal Studio',
  },
  {
    id: 'weigh_station',
    name: 'Weigh Station',
    unsupported: ['ap-southeast-1', 'ap-southeast-5'],
  },
  { id: 'wellness_center_and_services', name: 'Wellness Center and Services' },
  { id: 'wholesale_store', name: 'Wholesale Store' },
  { id: 'wild_animal_park', name: 'Wild Animal Park' },
  { id: 'wildlife_refuge', name: 'Wildlife Refuge' },
  { id: 'wine_and_liquor', name: 'Wine and Liquor' },
  { id: 'winery', name: 'Winery' },
  { id: "women's_apparel", name: "Women's Apparel" },
  { id: 'zoo', name: 'Zoo' },
]

export function placeCategory(id: string): PlaceCategory | undefined {
  return PLACE_CATEGORIES.find((c) => c.id === id)
}
